package com.mango.player.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.mango.player.bean.MusicList;

import com.mango.player.dao.MusicListDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig musicListDaoConfig;

    private final MusicListDao musicListDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        musicListDaoConfig = daoConfigMap.get(MusicListDao.class).clone();
        musicListDaoConfig.initIdentityScope(type);

        musicListDao = new MusicListDao(musicListDaoConfig, this);

        registerDao(MusicList.class, musicListDao);
    }
    
    public void clear() {
        musicListDaoConfig.getIdentityScope().clear();
    }

    public MusicListDao getMusicListDao() {
        return musicListDao;
    }

}
